Register login: OTP flow
quintype/malibu pull request #628
Opened 2021-02-17 04:47 UTC by Harshith46

2021-02-17 06:23 UTC, Harshith46 commented
remove then and use async and await

2021-02-24 04:19 UTC, Athira001 requested changes

2021-02-24 04:19 UTC, Athira001 commented on app/isomorphic/components/molecules/forms/otp.js
>            <button aria-label="verify-otp-button" onClick={otpHandler} className="malibu-btn-large">
can we make it an atom?

2021-02-24 04:51 UTC, Athira001 approved these changes

2021-02-24 11:05 UTC, merged