feat Progressive image loading
quintype/malibu pull request #770
Opened 2021-05-27 09:39 UTC by Harshith46

# Description

we are rendering a smaller size image on the initial load and then loading a higher quality of the image after few seconds. Doing this will improve page performance as we render a smaller size image initially. this size, time to load high quality image and other params are configurable from bk

Fixes: https://github.com/quintype/ace-planning/issues/419

Documentation: will taken in diff pr

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] tested locally and on staging for backend compatibity
- [ ] check the improved scores on page speed insights

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-05-27 10:00 UTC, Jeevan-Kishore requested changes
There were issues with huge DOM, multiple / duplicate API requests. Are those sorted?

2021-05-27 10:22 UTC, Deokumarjnu commented on app/isomorphic/components/atoms/card-image/card-image.m.css
> +  background-color: lightgray;
is this color defined anywhere?

2021-05-31 04:38 UTC, Harshith46 commented on app/isomorphic/components/atoms/card-image/index.js
> +      setTimeout(() => {
sure

2021-05-31 04:38 UTC, Harshith46 commented on app/isomorphic/components/atoms/card-image/card-image.m.css
> +  background-color: lightgray;
will add variable name

2021-05-31 04:38 UTC, Harshith46 commented on app/isomorphic/components/atoms/card-image/index.js
> +    if (isInitRow && progressiveImageConfig.is_enable) {
mention about the isInitrow condition

2021-05-31 05:23 UTC, ags1773 approved these changes
Looks good, provided there's a more detailed explanation for `isInitRow`

2021-05-31 05:23 UTC, Deokumarjnu approved these changes

2021-05-31 05:25 UTC, Athira001 approved these changes

2021-06-01 05:45 UTC, Jeevan-Kishore requested changes
Can i find documentation of this somewhere?

2021-06-01 05:45 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +      const timer = () => {
clearly this wont work. Please take care on what's returned and what isn't from a function

2021-06-01 05:45 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +        setTimeout(() => {
carve out function definition and only call in useEffect

2021-06-01 05:45 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +      {story["hero-image-s3-key"] && (
```suggestion
      !story["hero-image-s3-key"] return null;
```

2021-06-01 05:45 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +      {story["hero-image-s3-key"] && (
Use a function if need be

2021-06-01 06:09 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +import { get } from "lodash";
```suggestion
import get from "lodash/get";
```

2021-06-01 06:10 UTC, Jeevan-Kishore commented on app/isomorphic/components/atoms/card-image/index.js
> +        setPerfObj(progressiveImageConfig.subsequent_load);
clear timer once, not on unmount

2021-06-01 06:11 UTC, Jeevan-Kishore approved these changes
Approved with comments

2021-06-01 09:24 UTC, Harshith46 commented
docs: https://github.com/quintype/malibu/pull/772

2021-06-01 10:05 UTC, merged